export const CATEGORIES = [
  "crm_sales",
  "support_helpdesk",
  "communications",
  "marketing",
  "ecommerce",
  "data_seo_scraping",
  "developer_infra",
  "productivity",
  "finance",
  "ai_research_media",
] as const

export const AUTH_METHODS = [
  "oauth2",
  "api_key",
  "basic",
  "token",
  "other",
] as const

export const ACCESS_MODELS = [
  "self_serve",
  "paid_plan",
  "admin_approval",
  "partnership",
  "unknown",
] as const

export const API_STYLES = [
  "rest",
  "graphql",
  "sdk",
  "mcp",
  "none",
  "unknown",
] as const

export const API_BREADTH = ["thin", "moderate", "broad", "unknown"] as const

export const BUILDABILITY = [
  "ready",
  "caveats",
  "blocked",
  "unknown",
] as const

export type Category = (typeof CATEGORIES)[number]
export type AuthMethod = (typeof AUTH_METHODS)[number]
export type AccessModel = (typeof ACCESS_MODELS)[number]
export type ApiStyle = (typeof API_STYLES)[number]
export type ApiBreadth = (typeof API_BREADTH)[number]
export type Buildability = (typeof BUILDABILITY)[number]
export type ComposioToolkitKind = "rest" | "mcp"

export const categoryLabels: Record<Category, string> = {
  crm_sales: "CRM & Sales",
  support_helpdesk: "Support",
  communications: "Communications",
  marketing: "Marketing",
  ecommerce: "Ecommerce",
  data_seo_scraping: "Data & SEO",
  developer_infra: "Developer",
  productivity: "Productivity",
  finance: "Finance",
  ai_research_media: "AI & Research",
}

export const authLabels: Record<AuthMethod, string> = {
  oauth2: "OAuth2",
  api_key: "API key",
  basic: "Basic",
  token: "Token",
  other: "Other",
}

export const accessLabels: Record<AccessModel, string> = {
  self_serve: "Self-serve",
  paid_plan: "Paid plan",
  admin_approval: "Admin approval",
  partnership: "Partnership",
  unknown: "Unknown",
}

export const buildabilityLabels: Record<Buildability, string> = {
  ready: "Ready",
  caveats: "Caveats",
  blocked: "Blocked",
  unknown: "Unknown",
}

export type AppResearch = {
  /** README list number 1–100 */
  rank: number
  name: string
  website: string
  category: Category
  oneLiner: string | null

  /** Agent findings — null until researched */
  authMethods: AuthMethod[] | null
  access: AccessModel | null
  apiStyles: ApiStyle[] | null
  apiBreadth: ApiBreadth | null
  hasOfficialMcp: boolean | null
  buildability: Buildability | null
  blocker: string | null
  docsUrl: string | null
  evidenceNotes: string | null

  /** Ground truth from README + data/*.md */
  composioInCatalog: boolean
  composioSlug: string | null
  composioToolkitKind: ComposioToolkitKind | null
}

type SeedApp = Pick<
  AppResearch,
  | "rank"
  | "name"
  | "website"
  | "category"
  | "composioInCatalog"
  | "composioSlug"
  | "composioToolkitKind"
>

const RESEARCH_DEFAULTS = {
  oneLiner: null,
  authMethods: null,
  access: null,
  apiStyles: null,
  apiBreadth: null,
  hasOfficialMcp: null,
  buildability: null,
  blocker: null,
  docsUrl: null,
  evidenceNotes: null,
} satisfies Omit<AppResearch, keyof SeedApp>

function seed(apps: SeedApp[]): AppResearch[] {
  return apps.map((app) => ({ ...RESEARCH_DEFAULTS, ...app }))
}

export const apps: AppResearch[] = seed([
  {
    rank: 1,
    name: "Salesforce",
    website: "salesforce.com",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "salesforce",
    composioToolkitKind: "rest",
  },
  {
    rank: 2,
    name: "HubSpot",
    website: "hubspot.com",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "hubspot",
    composioToolkitKind: "rest",
  },
  {
    rank: 3,
    name: "Pipedrive",
    website: "pipedrive.com",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "pipedrive",
    composioToolkitKind: "rest",
  },
  {
    rank: 4,
    name: "Attio",
    website: "attio.com",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "attio",
    composioToolkitKind: "rest",
  },
  {
    rank: 5,
    name: "Twenty",
    website: "twenty.com",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "twenty",
    composioToolkitKind: "rest",
  },
  {
    rank: 6,
    name: "Podio",
    website: "podio.com",
    category: "crm_sales",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 7,
    name: "Zoho CRM",
    website: "zoho.com/crm",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "zoho",
    composioToolkitKind: "rest",
  },
  {
    rank: 8,
    name: "Close",
    website: "close.com",
    category: "crm_sales",
    composioInCatalog: true,
    composioSlug: "close",
    composioToolkitKind: "rest",
  },
  {
    rank: 9,
    name: "Copper",
    website: "copper.com",
    category: "crm_sales",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 10,
    name: "DealCloud",
    website: "api.docs.dealcloud.com",
    category: "crm_sales",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 11,
    name: "Zendesk",
    website: "zendesk.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "zendesk",
    composioToolkitKind: "rest",
  },
  {
    rank: 12,
    name: "Intercom",
    website: "intercom.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "intercom",
    composioToolkitKind: "rest",
  },
  {
    rank: 13,
    name: "Freshdesk",
    website: "freshdesk.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "freshdesk",
    composioToolkitKind: "rest",
  },
  {
    rank: 14,
    name: "Front",
    website: "front.com",
    category: "support_helpdesk",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 15,
    name: "Pylon",
    website: "usepylon.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "pylon_mcp",
    composioToolkitKind: "mcp",
  },
  {
    rank: 16,
    name: "LiveAgent",
    website: "liveagent.com",
    category: "support_helpdesk",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 17,
    name: "Plain",
    website: "plain.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "plain",
    composioToolkitKind: "rest",
  },
  {
    rank: 18,
    name: "Help Scout",
    website: "helpscout.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "help_scout",
    composioToolkitKind: "rest",
  },
  {
    rank: 19,
    name: "Gorgias",
    website: "gorgias.com",
    category: "support_helpdesk",
    composioInCatalog: true,
    composioSlug: "gorgias",
    composioToolkitKind: "rest",
  },
  {
    rank: 20,
    name: "Gladly",
    website: "gladly.com",
    category: "support_helpdesk",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 21,
    name: "Slack",
    website: "slack.com",
    category: "communications",
    composioInCatalog: true,
    composioSlug: "slack",
    composioToolkitKind: "rest",
  },
  {
    rank: 22,
    name: "Twilio",
    website: "twilio.com",
    category: "communications",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 23,
    name: "Zoho Cliq",
    website: "zoho.com/cliq",
    category: "communications",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 24,
    name: "Lark",
    website: "open.larksuite.com",
    category: "communications",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 25,
    name: "Pumble",
    website: "pumble.com",
    category: "communications",
    composioInCatalog: true,
    composioSlug: "pumble",
    composioToolkitKind: "rest",
  },
  {
    rank: 26,
    name: "Discord",
    website: "discord.com",
    category: "communications",
    composioInCatalog: true,
    composioSlug: "discord",
    composioToolkitKind: "rest",
  },
  {
    rank: 27,
    name: "Telegram",
    website: "core.telegram.org",
    category: "communications",
    composioInCatalog: true,
    composioSlug: "telegram",
    composioToolkitKind: "rest",
  },
  {
    rank: 28,
    name: "WhatsApp Business",
    website: "developers.facebook.com/docs/whatsapp",
    category: "communications",
    composioInCatalog: true,
    composioSlug: "whatsapp",
    composioToolkitKind: "rest",
  },
  {
    rank: 29,
    name: "Aircall",
    website: "aircall.io",
    category: "communications",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 30,
    name: "Vonage",
    website: "developer.vonage.com",
    category: "communications",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 31,
    name: "Google Ads",
    website: "developers.google.com/google-ads",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "googleads",
    composioToolkitKind: "rest",
  },
  {
    rank: 32,
    name: "Meta Ads",
    website: "developers.facebook.com/docs/marketing-apis",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "metaads",
    composioToolkitKind: "rest",
  },
  {
    rank: 33,
    name: "LinkedIn Ads",
    website: "learn.microsoft.com/linkedin/marketing",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "linkedin_ads",
    composioToolkitKind: "rest",
  },
  {
    rank: 34,
    name: "GoHighLevel",
    website: "highlevel.stoplight.io",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "highlevel",
    composioToolkitKind: "rest",
  },
  {
    rank: 35,
    name: "Mailchimp",
    website: "mailchimp.com/developer",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "mailchimp",
    composioToolkitKind: "rest",
  },
  {
    rank: 36,
    name: "Klaviyo",
    website: "developers.klaviyo.com",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "klaviyo",
    composioToolkitKind: "rest",
  },
  {
    rank: 37,
    name: "systeme.io",
    website: "systeme.io",
    category: "marketing",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 38,
    name: "Pinterest",
    website: "developers.pinterest.com",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "pinterest",
    composioToolkitKind: "rest",
  },
  {
    rank: 39,
    name: "Threads",
    website: "developers.facebook.com/docs/threads",
    category: "marketing",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 40,
    name: "SendGrid",
    website: "sendgrid.com",
    category: "marketing",
    composioInCatalog: true,
    composioSlug: "sendgrid",
    composioToolkitKind: "rest",
  },
  {
    rank: 41,
    name: "Shopify",
    website: "shopify.dev",
    category: "ecommerce",
    composioInCatalog: true,
    composioSlug: "shopify",
    composioToolkitKind: "rest",
  },
  {
    rank: 42,
    name: "WooCommerce",
    website: "woocommerce.com/document/woocommerce-rest-api",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 43,
    name: "BigCommerce",
    website: "developer.bigcommerce.com",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 44,
    name: "Salesforce Commerce Cloud",
    website: "developer.salesforce.com/docs/commerce",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 45,
    name: "Magento",
    website: "developer.adobe.com/commerce",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 46,
    name: "Squarespace",
    website: "developers.squarespace.com",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 47,
    name: "Ecwid",
    website: "api-docs.ecwid.com",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 48,
    name: "Gumroad",
    website: "gumroad.com/api",
    category: "ecommerce",
    composioInCatalog: true,
    composioSlug: "gumroad",
    composioToolkitKind: "rest",
  },
  {
    rank: 49,
    name: "Amazon Selling Partner",
    website: "developer-docs.amazon.com/sp-api",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 50,
    name: "fanbasis",
    website: "fanbasis.com",
    category: "ecommerce",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 51,
    name: "DataForSEO",
    website: "docs.dataforseo.com",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "dataforseo",
    composioToolkitKind: "rest",
  },
  {
    rank: 52,
    name: "SE Ranking",
    website: "seranking.com/api",
    category: "data_seo_scraping",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 53,
    name: "Ahrefs",
    website: "ahrefs.com/api",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "ahrefs",
    composioToolkitKind: "rest",
  },
  {
    rank: 54,
    name: "MrScraper",
    website: "docs.mrscraper.com",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "mrscraper",
    composioToolkitKind: "rest",
  },
  {
    rank: 55,
    name: "Apify",
    website: "docs.apify.com",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "apify",
    composioToolkitKind: "rest",
  },
  {
    rank: 56,
    name: "Firecrawl",
    website: "firecrawl.dev",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "firecrawl",
    composioToolkitKind: "rest",
  },
  {
    rank: 57,
    name: "Bright Data",
    website: "brightdata.com",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "brightdata",
    composioToolkitKind: "rest",
  },
  {
    rank: 58,
    name: "Sherlock",
    website: "github.com/sherlock-project/sherlock",
    category: "data_seo_scraping",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 59,
    name: "Waterfall.io",
    website: "waterfall.io",
    category: "data_seo_scraping",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 60,
    name: "Clay",
    website: "clay.com",
    category: "data_seo_scraping",
    composioInCatalog: true,
    composioSlug: "clay",
    composioToolkitKind: "rest",
  },
  {
    rank: 61,
    name: "GitHub",
    website: "docs.github.com/rest",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "github",
    composioToolkitKind: "rest",
  },
  {
    rank: 62,
    name: "Vercel",
    website: "vercel.com/docs/rest-api",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "vercel",
    composioToolkitKind: "rest",
  },
  {
    rank: 63,
    name: "Netlify",
    website: "docs.netlify.com/api",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "netlify_mcp",
    composioToolkitKind: "mcp",
  },
  {
    rank: 64,
    name: "Cloudflare",
    website: "developers.cloudflare.com/api",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "cloudflare",
    composioToolkitKind: "rest",
  },
  {
    rank: 65,
    name: "Supabase",
    website: "supabase.com/docs",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "supabase",
    composioToolkitKind: "rest",
  },
  {
    rank: 66,
    name: "Neo4j",
    website: "neo4j.com/docs/api",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "neo4j",
    composioToolkitKind: "rest",
  },
  {
    rank: 67,
    name: "Snowflake",
    website: "docs.snowflake.com",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "snowflake",
    composioToolkitKind: "rest",
  },
  {
    rank: 68,
    name: "MongoDB Atlas",
    website: "mongodb.com/docs/atlas/api",
    category: "developer_infra",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 69,
    name: "Datadog",
    website: "docs.datadoghq.com/api",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "datadog",
    composioToolkitKind: "rest",
  },
  {
    rank: 70,
    name: "Sentry",
    website: "docs.sentry.io/api",
    category: "developer_infra",
    composioInCatalog: true,
    composioSlug: "sentry",
    composioToolkitKind: "rest",
  },
  {
    rank: 71,
    name: "Notion",
    website: "developers.notion.com",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "notion",
    composioToolkitKind: "rest",
  },
  {
    rank: 72,
    name: "Airtable",
    website: "airtable.com/developers",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "airtable",
    composioToolkitKind: "rest",
  },
  {
    rank: 73,
    name: "Linear",
    website: "developers.linear.app",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "linear",
    composioToolkitKind: "rest",
  },
  {
    rank: 74,
    name: "Jira",
    website: "developer.atlassian.com",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "jira",
    composioToolkitKind: "rest",
  },
  {
    rank: 75,
    name: "Asana",
    website: "developers.asana.com",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "asana",
    composioToolkitKind: "rest",
  },
  {
    rank: 76,
    name: "Monday.com",
    website: "developer.monday.com",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "monday",
    composioToolkitKind: "rest",
  },
  {
    rank: 77,
    name: "ClickUp",
    website: "clickup.com/api",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "clickup",
    composioToolkitKind: "rest",
  },
  {
    rank: 78,
    name: "Coda",
    website: "coda.io/developers",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "coda",
    composioToolkitKind: "rest",
  },
  {
    rank: 79,
    name: "Smartsheet",
    website: "smartsheet.com/developers",
    category: "productivity",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 80,
    name: "Harvest",
    website: "harvestapp.com",
    category: "productivity",
    composioInCatalog: true,
    composioSlug: "harvest",
    composioToolkitKind: "rest",
  },
  {
    rank: 81,
    name: "Stripe",
    website: "stripe.com/docs/api",
    category: "finance",
    composioInCatalog: true,
    composioSlug: "stripe",
    composioToolkitKind: "rest",
  },
  {
    rank: 82,
    name: "Plaid",
    website: "plaid.com/docs",
    category: "finance",
    composioInCatalog: true,
    composioSlug: "plaid_mcp",
    composioToolkitKind: "mcp",
  },
  {
    rank: 83,
    name: "Binance",
    website: "binance-docs.github.io",
    category: "finance",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 84,
    name: "Paygent Connect",
    website: "paygent",
    category: "finance",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 85,
    name: "iPayX",
    website: "ipayx.ai/docs",
    category: "finance",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 86,
    name: "QuickBooks",
    website: "developer.intuit.com",
    category: "finance",
    composioInCatalog: true,
    composioSlug: "quickbooks",
    composioToolkitKind: "rest",
  },
  {
    rank: 87,
    name: "Xero",
    website: "developer.xero.com",
    category: "finance",
    composioInCatalog: true,
    composioSlug: "xero",
    composioToolkitKind: "rest",
  },
  {
    rank: 88,
    name: "Brex",
    website: "developer.brex.com",
    category: "finance",
    composioInCatalog: true,
    composioSlug: "brex",
    composioToolkitKind: "rest",
  },
  {
    rank: 89,
    name: "Ramp",
    website: "docs.ramp.com",
    category: "finance",
    composioInCatalog: true,
    composioSlug: "ramp",
    composioToolkitKind: "rest",
  },
  {
    rank: 90,
    name: "PitchBook",
    website: "pitchbook.com",
    category: "finance",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 91,
    name: "NotebookLM",
    website: "cloud.google.com/gemini",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "notebook_lm",
    composioToolkitKind: "rest",
  },
  {
    rank: 92,
    name: "Otter AI",
    website: "help.otter.ai",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "otter_ai_mcp",
    composioToolkitKind: "mcp",
  },
  {
    rank: 93,
    name: "Fathom",
    website: "fathom.video",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "fathom",
    composioToolkitKind: "rest",
  },
  {
    rank: 94,
    name: "Consensus",
    website: "consensus.app",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "consensus",
    composioToolkitKind: "rest",
  },
  {
    rank: 95,
    name: "Reducto",
    website: "reducto.ai",
    category: "ai_research_media",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 96,
    name: "Devin",
    website: "docs.devin.ai",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "devin_mcp",
    composioToolkitKind: "mcp",
  },
  {
    rank: 97,
    name: "higgsfield",
    website: "higgsfield.ai/cli",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "higgsfield_mcp",
    composioToolkitKind: "mcp",
  },
  {
    rank: 98,
    name: "Mermaid CLI",
    website: "github.com/mermaid-js/mermaid-cli",
    category: "ai_research_media",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
  {
    rank: 99,
    name: "YouTube Transcript",
    website: "transcriptapi.com",
    category: "ai_research_media",
    composioInCatalog: true,
    composioSlug: "youtube_transcript",
    composioToolkitKind: "rest",
  },
  {
    rank: 100,
    name: "Grain",
    website: "grain.com",
    category: "ai_research_media",
    composioInCatalog: false,
    composioSlug: null,
    composioToolkitKind: null,
  },
])
